const products = [
    { id: 1, 
      src: '../images/product/product1.jpg', 
      src2: '../images/product/product1-2.jpg',
      src3: '../images/product/product1-3.jpg',
      src4: '../images/product/product1-4.jpg',
      name: 'Mens Formal Shirt' ,
      price: '159.00' ,
      quantity: 1,
      category: 'cat-men',
      subcategory: 'shirt',
      description: 'Navy blue, cotton, printed formal shirt by STOP. Expertly tailored from light cotton with a minimal print, this slim-fit shirt features a sharp cut-away collar, buttoned front, structured chest pocket, and full set-in sleeves, ensuring confidence and ease throughout your workday.',
     },

     { id: 2, 
        src: '../images/product/product2.jpg', 
        src2: '../images/product/product2-2.jpg',
        src3: '../images/product/product2-3.jpg',
        src4: '../images/product/product2-4.jpg',
        name: 'Womens Dress' ,
        price: '169.00' ,
        quantity: 1,
        category: 'cat-women',
        subcategory: 'dress',
        description: 'Experience elegance and comfort with our womens polyester dress, designed for party occasions. With a sleek, sophisticated solid pattern, this premium dress combines durability and luxury. Perfect for brunch, dinners, or upscale events, it promises style and unmatched comfort. Make a statement with this exquisite piece.',
       },

       { id: 3, 
        src: '../images/product/product3.jpg', 
        src2: '../images/product/product3-2.jpg',
        src3: '../images/product/product3-3.jpg',
        src4: '../images/product/product3-4.jpg',
        name: 'Mens T-Shirt' ,
        price: '120.00' ,
        quantity: 1,
        category: 'cat-men',
        subcategory: 'tshirt',
        description: 'Elevate your casual style with this crisp white Fratini T-shirt. Crafted from a soft blend of fabrics, it offers both comfort and sophistication. The subtle navy and white trim at the collar adds a touch of understated elegance. A perfect choice for weekend outings or relaxed gatherings.',
       },
        
       { id: 4, 
        src: '../images/product/product4.jpg', 
        src2: '../images/product/product4-2.jpg',
        src3: '../images/product/product4-3.jpg',
        src4: '../images/product/product4-4.jpg',
        name: 'Womens Tote Bag' ,
        price: '132.00' ,
        quantity: 1,
        category: 'accessory',
        subcategory: 'bag',
        description: 'Beige textured solid tote bag, with cut work detail 1 main compartment, has a zip closure, 1 external pocket,With a detachable sling strap',
       },

       { id: 5, 
        src: '../images/product/product5.jpg', 
        src2: '../images/product/product5-2.jpg',
        src3: '../images/product/product5-3.jpg',
        src4: '../images/product/product5-4.jpg',
        name: 'Slim Fit Mens Jeans' ,
        price: '225.00' ,
        quantity: 1,
        category: 'cat-men',
        subcategory: 'jeans',
        description: 'Blue dark wash 5-pocket low-rise jeans, clean look, light fade, has a button and zip closure, and waistband with belt loops.',
       },

       { id: 6, 
        src: '../images/product/product6.jpg', 
        src2: '../images/product/product6-2.jpg',
        src3: '../images/product/product6-3.jpg',
        src4: '../images/product/product6-4.jpg',
        name: 'Womens PVC Belt' ,
        price: '69.00' ,
        quantity: 1,
        category: 'accessory',
        subcategory: 'belt',
        description: 'You can use these belts all year round. It’s comfortable to wear and adds a nice accent to your outfits! They can be matched for dress, baggy T-shirts, sweaters, long coats, long shirt and so on. An exquisite accessory for your daily wear and important occasions.',
       },

       { id: 7, 
        src: '../images/product/product7.jpg', 
        src2: '../images/product/product7-2.jpg',
        src3: '../images/product/product7-3.jpg',
        src4: '../images/product/product7-4.jpg',
        name: 'Mens Casual Shirt' ,
        price: '120.00' ,
        quantity: 1,
        category: 'cat-men',
        subcategory: 'shirt',
       },

       { id: 8, 
        src: '../images/product/product8.jpg', 
        src2: '../images/product/product8-2.jpg',
        src3: '../images/product/product8-3.jpg',
        src4: '../images/product/product8-4.jpg',
        name: 'Womens Sweatshirt' ,
        price: '102.00' ,
        quantity: 1,
        category: 'cat-women',
        subcategory: 'tshirt',
       },
  ];
  
  export default products;