const products = [
    { id: 1, 
      src: '../images/product/product1.jpg', 
      src2: '../images/product/product1-2.jpg',
      src3: '../images/product/product1-3.jpg',
      src4: '../images/product/product1-4.jpg',
      name: 'Mens Formal Shirt' ,
      price: '159.00' ,
      quantity: 1,
      category: 'clothing',
     },

     { id: 2, 
        src: '../images/product/product2.jpg', 
        src2: '../images/product/product2-2.jpg',
        src3: '../images/product/product2-3.jpg',
        src4: '../images/product/product2-4.jpg',
        name: 'Womens Dress' ,
        price: '169.00' ,
        quantity: 1,
        category: 'clothing',
       },

       { id: 3, 
        src: '../images/product/product3.jpg', 
        src2: '../images/product/product3-2.jpg',
        src3: '../images/product/product3-3.jpg',
        src4: '../images/product/product3-4.jpg',
        name: 'Mens T-Shirt' ,
        price: '120.00' ,
        quantity: 1,
        category: 'clothing',
       },
        
       { id: 4, 
        src: '../images/product/product4.jpg', 
        src2: '../images/product/product4-2.jpg',
        src3: '../images/product/product4-3.jpg',
        src4: '../images/product/product4-4.jpg',
        name: 'Womens Tote Bag' ,
        price: '132.00' ,
        quantity: 1,
        category: 'accessory',
       },

       { id: 5, 
        src: '../images/product/product5.jpg', 
        src2: '../images/product/product5-2.jpg',
        src3: '../images/product/product5-3.jpg',
        src4: '../images/product/product5-4.jpg',
        name: 'Slim Fit Mens Jeans' ,
        price: '225.00' ,
        quantity: 1,
        category: 'clothing',
       },

       { id: 6, 
        src: '../images/product/product6.jpg', 
        src2: '../images/product/product6-2.jpg',
        src3: '../images/product/product6-3.jpg',
        src4: '../images/product/product6-4.jpg',
        name: 'Womens PVC Belt' ,
        price: '69.00' ,
        quantity: 1,
        category: 'accessory',
       },

       { id: 7, 
        src: '../images/product/product7.jpg', 
        src2: '../images/product/product7-2.jpg',
        src3: '../images/product/product7-3.jpg',
        src4: '../images/product/product7-4.jpg',
        name: 'Mens Casual Shirt' ,
        price: '120.00' ,
        quantity: 1,
        category: 'clothing',
       },

       { id: 8, 
        src: '../images/product/product8.jpg', 
        src2: '../images/product/product8-2.jpg',
        src3: '../images/product/product8-3.jpg',
        src4: '../images/product/product8-4.jpg',
        name: 'Womens Sweatshirt' ,
        price: '102.00' ,
        quantity: 1,
        category: 'clothing',
       },
  ];
  
  export default products;